name: Build

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            os: linux
            tar: tar
          - runner: macos-latest
            os: macos
            tar: gtar
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: macos install prerequisites
        if: matrix.os == 'macos'
        run: |
          brew install zlib texinfo gmp mpfr libmpc gnu-sed gawk isl expat
          brew cleanup
          brew reinstall gcc
          export PATH=/usr/local/opt/texinfo/bin:$PATH
      - name: verify gdc
        if: matrix.os == 'macos'
        run: which gdc-12
      - name: rename gdc
        if: matrix.os == 'macos'
        run: |
          ln -s /usr/local/bin/gdc-12 /usr/local/bin/gdc
          which gdc
      - name: ubuntu install prerequisites
        if: matrix.os == 'linux'
        run: sudo apt-get install gdc libgmp-dev libmpc-dev libmpfr-dev binutils-dev build-essential -y

      - name: Download
        run: ./download.sh

      - name: Build aarch64-none-elf
        run: ./build-gdc.sh aarch64-none-elf

      - name: Build riscv64-unknown-elf
        run: ./build-gdc.sh riscv64-unknown-elf

      - name: Package
        run: |
          ${{ matrix.tar }} -czf gnu-aarch64-none-elf-${{ matrix.os }}.tar.gz gnu-aarch64-none-elf
          ${{ matrix.tar }} -czf gnu-riscv64-unknown-elf-${{ matrix.os }}.tar.gz gnu-riscv64-unknown-elf
      - name: Upload Binaries
        uses: AButler/upload-release-assets@v2.0
        with:
          files: gnu-*.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
